services:
  redis:
    image: redis:8.8.1
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    environment:
      - REDIS_PASSWORD=mandingo23cm
      - loglevel=warning
      - REDIS_REPLICATION_MODE=master
      - name=redis
      - SKIP_FIX_PERMS=1
    #volumes:
    #  - ./redis-data:/data
  redisinsight:
    image: redis/redisinsight:3.8.0
    ports:
      - "5540:5540"
    #volumes:
    #  - ./redis-client:/data
    depends_on:
      - redis