version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directories:
      #- "/ansible/stuff/services/*"
      #- "/ansible/stuff/databases/*"
      - "/ansible/stuff/databases/sql/mariadb"
      - "/ansible/stuff/databases/sql/mysql"
      - "/ansible/stuff/databases/sql/oracle/**/*"
      #- "**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
