version: '3.7'

services:
  oracle-db-11g-xs:
    image: epiclabs/docker-oracle-xe-11g
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
      - 8080:8080
    volumes:
      - ./storage/:/u01/app/oracle
      - ./oracle-sql:/docker-entrypoint-initdb.d/
    environment:
      - ORACLE_ENABLE_XDB=true
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true