version: '3.6'
services:

  mongo:
    image: mongo:4.4
    restart: on-failure
    container_name: mongo
    # below entries activate --auth at mongodb which cannot be handled e.g by Graylog
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo/data/db:/data/db

  mongo-admin:
    image: mongo-express
    restart: always
    container_name: mongo-admin
    # below entries activate --auth in MongoDB
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
    ports:
      - "8950:8081"
    depends_on:
      - mongo
