services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.579
    ports:
      - "8082:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
  nexus:
    image: sonatype/nexus3:3.95.1
    container_name: nexus
    ports:
      - "8083:8081"
      - "443:443"
    #u ser: root # default user is a bit different one
    # below requires proper permissions on the host machine for the nexus-data folder
    #volumes:
    # - ./nexus:/nexus-data