version: '3.6'
services:
  nxlog:
    image: nxlog/nxlog-ce:2.10.2150
    container_name: nxlog
    volumes:
      - ./nxlog/config/nxlog.conf:/etc/nxlog.conf
      - ./nxlog/files/input:/var/log
      - ./nxlog/files/output:/lib
    restart: on-failure
    depends_on:
      - graylog

  graylog:
    image: graylog/graylog:4.2
    container_name: graylog
    ports:
      - "1514:1514"
      - "9000:9000"
      - "12201:12201"
    restart: on-failure
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_PASSWORD_SECRET=jakiesTamHasloPowinnoByc
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 #admin/admin
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - ./graylog/config/server.conf:/etc/graylog/server/server.conf
      - ./graylog/journal:/var/lib/graylog-server/journal
    links:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:4.4
    restart: on-failure
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data/db:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

# default admin/admin -> chnage password to admin1
# Marcin/Marcin1
