version: '3.6'

services:

  # http://localhost:8080/hello
  # http://localhost:8080/__admin/mappings

  wiremock:
    image: wiremock/wiremock:2.33.2
    ports:
      - "8080:8080"
      - "8443:8443"
    #volumes:
    #  - ./data:/home/wiremock
    #environment:
    #  - https-port=8443
    #  - verbose=true