version: '3.6'

services:

  wiremock:
    image: wiremock/wiremock:2.33.2
    ports:
      - "8080:8080"8
      - "8443:8443"
    volumes:
      - ./data:/home/wiremock
   # command: '--https-port 8443 --verbose' # enables HTTP