services:
  elasticsearch:
    image: elasticsearch:9.4.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - http.host=elasticsearch
      - discovery.type=single-node
    # must be locally writable by the Elasticsearch process (UID 1000)
    #volumes:
    #  - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:9.4.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml