version: "3.7"

services:

  # http://localhost:8089/guacamole
  guacamole:
    image: guacamole/guacamole:1.4.0
    ports:
      - "8089:8080" # guacadmin/guacadmin
    depends_on:
      - guacd
      - mysql
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      GUACD_PORT: "4822"
      GUACD_HOSTNAME: guacd
    links:
      - mysql:mysql
      - guacd:guacd

  guacd:
    image: guacamole/guacd:1.4.0
    ports:
      - "4822:4822"
      - "5900:5900" # VNC port
      - "3389:3389" # RDP port
    environment:
      ENABLE_WEBSOCKET: "true"
      GUACD_LOG_LEVEL: "debug" # debug

  mysql:
    image: mysql:8.0.16
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./stuff/infra/mysql/sql:/docker-entrypoint-initdb.d/
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root # root/root
    command: --default-authentication-plugin=mysql_native_password