version: '3.7'

services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    restart: always
    ports:
      - "33060:33060"
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rocco
      - MYSQL_PASSWORD=rocco
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1