version: '3.6'

services:
  #http://localhost:9000 admin/admin
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    volumes:
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
      
